service: lai-new

frameworkVersion: '2'

custom:
  projectName: lai-new
  stage: dev
  region: us-east-1
  queueName: AsyncTaskSQS.fifo
  dynamoDBTableName: ${self:custom.projectName}-${self:custom.stage}-table
  s3BucketName: ${self:custom.projectName}-${self:custom.stage}-s3-bucket
  userPoolName: ${self:custom.projectName}-${self:custom.stage}
  clientName: ${self:custom.projectName}-client
  domainName: ${self:custom.projectName}-${self:custom.stage}
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  environment:
    DB_TABLE_NAME: ${self:custom.dynamoDBTableName}
    S3_BUCKET_NAME: ${self:custom.s3BucketName}
    APP_REGION: ${self:custom.region}
    USER_POOL_ID: !Ref CognitoUserPool
    USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient
    APP_ID: ${file(config/env.yml):${self:custom.stage}.appId}
    APP_SECRET: ${file(config/env.yml):${self:custom.stage}.appSecret}
    CALL_BACK_URL: ${file(config/env.yml):${self:custom.stage}.callBackUrl}
    STRIPE_KEY: ${file(config/env.yml):${self:custom.stage}.stripeKey}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ UserTable, Arn ]
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
        - 's3:ListBucket'
      Resource: 
        - "arn:aws:s3:::${self:custom.s3BucketName}/*"
        - "arn:aws:s3:::${self:custom.s3BucketName}"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        Fn::GetAtt: [ SQSQueue, Arn ]

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-python-requirements
  - serverless-offline

functions:
  - ${file(src/auth/functions.yml)}
  - ${file(src/campaign/functions.yml)}
  - ${file(src/ads/functions.yml)}

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/sqs.yml)}
